//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighingStation.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SendWeighingData", ReplyAction="http://tempuri.org/IDataService/SendWeighingDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ArrayList))]
        string SendWeighingData(System.Collections.ArrayList inData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/AddWeighingStation", ReplyAction="http://tempuri.org/IDataService/AddWeighingStationResponse")]
        string AddWeighingStation(ref int outWeighingStationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAmountOfWeighingStations", ReplyAction="http://tempuri.org/IDataService/GetAmountOfWeighingStationsResponse")]
        int GetAmountOfWeighingStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SetAmountOfWeighingStations", ReplyAction="http://tempuri.org/IDataService/SetAmountOfWeighingStationsResponse")]
        string SetAmountOfWeighingStations(int inValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAmountOfMaximumWeighingStations", ReplyAction="http://tempuri.org/IDataService/GetAmountOfMaximumWeighingStationsResponse")]
        int GetAmountOfMaximumWeighingStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/SetAmountOfMaximumWeighingStations", ReplyAction="http://tempuri.org/IDataService/SetAmountOfMaximumWeighingStationsResponse")]
        string SetAmountOfMaximumWeighingStations(int inValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/PopulateVariables", ReplyAction="http://tempuri.org/IDataService/PopulateVariablesResponse")]
        void PopulateVariables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetLastTenItems", ReplyAction="http://tempuri.org/IDataService/GetLastTenItemsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ArrayList))]
        System.Collections.ArrayList GetLastTenItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUnderweightItems", ReplyAction="http://tempuri.org/IDataService/GetUnderweightItemsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ArrayList))]
        System.Collections.ArrayList GetUnderweightItems();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : WeighingStation.ServiceReference1.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<WeighingStation.ServiceReference1.IDataService>, WeighingStation.ServiceReference1.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendWeighingData(System.Collections.ArrayList inData) {
            return base.Channel.SendWeighingData(inData);
        }
        
        public string AddWeighingStation(ref int outWeighingStationID) {
            return base.Channel.AddWeighingStation(ref outWeighingStationID);
        }
        
        public int GetAmountOfWeighingStations() {
            return base.Channel.GetAmountOfWeighingStations();
        }
        
        public string SetAmountOfWeighingStations(int inValue) {
            return base.Channel.SetAmountOfWeighingStations(inValue);
        }
        
        public int GetAmountOfMaximumWeighingStations() {
            return base.Channel.GetAmountOfMaximumWeighingStations();
        }
        
        public string SetAmountOfMaximumWeighingStations(int inValue) {
            return base.Channel.SetAmountOfMaximumWeighingStations(inValue);
        }
        
        public void PopulateVariables() {
            base.Channel.PopulateVariables();
        }
        
        public System.Collections.ArrayList GetLastTenItems() {
            return base.Channel.GetLastTenItems();
        }
        
        public System.Collections.ArrayList GetUnderweightItems() {
            return base.Channel.GetUnderweightItems();
        }
    }
}
